version: "3.9"

services:
  postgres-shard1:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./data/shard1:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  postgres-shard2:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5434:5432
    volumes:
      - ./data/shard2:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  postgres-shard3:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5435:5432
    volumes:
      - ./data/shard3:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  data:
    driver: local
