CREATE TABLE grades_parts (id SERIAL NOT NULL, g INT NOT NULL) PARTITION BY RANGE(g);

CREATE TABLE g0035 (LIKE grades_parts INCLUDING INDEXES);
CREATE TABLE g3560 (LIKE grades_parts INCLUDING INDEXES);
CREATE TABLE g6080 (LIKE grades_parts INCLUDING INDEXES);
CREATE TABLE g80100 (LIKE grades_parts INCLUDING INDEXES);

ALTER TABLE grades_parts ATTACH PARTITION g0035 FOR VALUES FROM (0) to (35);
ALTER TABLE grades_parts ATTACH PARTITION g3560 FOR VALUES FROM (35) to (60);
ALTER TABLE grades_parts ATTACH PARTITION g6080 FOR VALUES FROM (60) to (80);
ALTER TABLE grades_parts ATTACH PARTITION g80100 FOR VALUES FROM (80) to (100);